// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtTp3jtvkwK8MR8xiZ3lD7mC-2RnmwSxM',
    appId: '1:92051252827:web:19e844a36a789d04c8417e',
    messagingSenderId: '92051252827',
    projectId: 'lkblocks',
    authDomain: 'lkblocks.firebaseapp.com',
    storageBucket: 'lkblocks.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBs546BcJ9LDqKe4rQ7rdFMay9pEzmmQoQ',
    appId: '1:92051252827:android:30e89dde14fa5b46c8417e',
    messagingSenderId: '92051252827',
    projectId: 'lkblocks',
    storageBucket: 'lkblocks.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1kcKr5hbEQDhYCiCftSWTfvLv_r8rxh8',
    appId: '1:92051252827:ios:db91da7d4d4d9001c8417e',
    messagingSenderId: '92051252827',
    projectId: 'lkblocks',
    storageBucket: 'lkblocks.appspot.com',
    iosBundleId: 'com.example.blocksapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1kcKr5hbEQDhYCiCftSWTfvLv_r8rxh8',
    appId: '1:92051252827:ios:b01c8e58ebf8f45dc8417e',
    messagingSenderId: '92051252827',
    projectId: 'lkblocks',
    storageBucket: 'lkblocks.appspot.com',
    iosBundleId: 'com.example.blocksapp.RunnerTests',
  );
}
